### ISSUE TITLE
Something wrong with assert declaration?

### ISSUE THREAD

**Issue by devdavidkarlsson** [jhurt/FLACiOS#3]
/FLACiOS-master/libFLAC/src/libFLAC++/metadata.cpp:276:4: Use of undeclared identifier 'assert'

**Comment by agamirzov** [comment]
Same problem. Has anyone found a solution?

**Comment by mahboud** [comment]
In FLAC's assert.h, change:
`#include <assert.h>`
To:
`#include_next <assert.h>`

**Comment by jhurt** [comment]
Thanks @mahboud, I pushed this change to master.
